### ISSUE TITLE
ESC exit issue in v1.3 configuration menu

### ISSUE THREAD

**Issue by chrisa850** [ThorstenBr/A2DVI-Firmware#14]
It appears that the v1.3 configuration program will not update the DVI output when using ESC to exit from a sub-menu. The program does in fact exit, and the composite output shows the exit message and a floating point prompt, but the DVI output still shows the configuration menu.

As an example (using the DOS 3.3 disk image), press S for save to flash, and immediately press ESC. The configuration menu will remain on the DVI output. only a reset will clear the configuration menu from DVI.

On the other hand, If you were to have pressed a key that brought you back to the main menu, the program would exit normally on DVI and composite.

**Comment by ThorstenBr** [comment]
Thanks for the report. I see what has happened. Will be an easy fix.

For the moment, just press any other key after entering a submenu or pressing save - except for ESC. Then press ESC afterwards.
Or just press CTRL-RESET - like one usually needs to anyway, to boot into any other program.
