### ISSUE TITLE
720p support

### ISSUE THREAD

**Issue by dhgoss** [ThorstenBr/A2DVI-Firmware#4]
Hi! This is an awesome project.  I built up a board using Palle's schematic, and it works great on my monitor and also 2 older TV's I have.  However, on the two Vizio TV's I have it does not work.  Apparently, the minimum resolution they can display with HDMI is 720p.  I found this commit on github for 720x480 resolution: https://github.com/DLehenbauer/econopet/commit/5c511b626f7eae74e0c19a83014e3847072340e3
I forked your project and am going to experiment with 720p mode.  I'm thinking of using one of the unused gpio pins as an input switch so I can switch between the standard resolution and 720p mode.  However, there is an open issue with the official Pi Pico extension in VS  Code using Windows so I am unable to import your project to compile with VS Code.  I was wondering what method you are using to compile your project?  I do have a linux machine with Ubuntu so could use that perhaps to compile.  Thanks!  Dan

**Comment by ThorstenBr** [comment]
720x480 further increases the load and required data throughput - so not sure if the A2DVI-Firmware could still handle this on PICO. Rendering and data transmission all have to fit on a single CPU core. HIRES and Double-HIRES are the most demanding modes. Might still work - or maybe not. You have to test and see. In case it doesn't work, you have the chance of switching to the new PICO2 though. Its got a new generation of ARM cores, which are even more powerful.

I just use the standard toolchain to build on Linux. Requires cmake, GNU Make and the arm cross-compiler (gcc-arm-non-eabi). Should all be available as packets for Ubuntu. Also requires the latest PICO SDK (2.0). I would clone that directly from github. You can build from the command-line (cmake / make) - or add it as a build command to your favorite Linux editor / IDE.

**Comment by ThorstenBr** [comment]
I actually gave this a try. 720x480p are actually also working with PICO.
Here's a quick build - not really tested much, but seems to work:
[A2DVI_v1.0_720x480p.zip](https://github.com/user-attachments/files/16877289/A2DVI_v1.0_720x480p.zip)
Of course this does result in a different aspect ratio though...

**Comment by dhgoss** [comment]
Works great on my TV now with 720x480.  Thanks!

**Comment by ThorstenBr** [comment]
Might be a feature for the future: adding a menu option to switch video modes (640x480 vs 720x480).

**Comment by dhgoss** [comment]
I've been running it continuously in 720x480 mode for 2 days.  Everything seems fine so far.

**Comment by misterblack1** [comment]
Oh this is great, +1 on the ability to pick either resolution in the config utility would be awesome. 720x480 is closer DVD / Bluray players output so is likely more widely compatible. I think 640 also results in the Apple II image being a little stretched horizontally versus reality so that might be resolved with 720 anyway.

**Comment by ThorstenBr** [comment]
Firmware v1.6 now supports switching between 640x480 and 720x480 video output.
