### ISSUE TITLE
Selective monochrome mode while in DHGR

### ISSUE THREAD

**Issue by misterblack1** [ThorstenBr/A2DVI-Firmware#8]
Hi, I noticed that when using RGB output on my Enhancer IIe, Dazzle draw seems to use some kind of selective monochrome mode on both the splash screen and while using the program. I'm not positive how this is working, but it's a nice effect that really cleans up the text. Could this be replicated in the the firmware for the A2DVI? Seems like this may be some long-forgotten feature of RGB cards that could be used today to make modern programs look better when used with cards like A2DVI. 

Examples:
![Dazzle Draw Video 7 Enahcner IIe](https://github.com/user-attachments/assets/9ef5758b-b325-458b-bb75-64b2941ef538)
![Dazzle Draw Video 7 Enhancer IIe Splash](https://github.com/user-attachments/assets/6637060f-df9c-4987-b9bb-a749f8799e23)

Thanks

**Comment by ThorstenBr** [comment]
I have a suspicion how that could have worked. Basically the only way I could think of: switching video modes and settings back and forth in between lines, or even in between pixels of a line.

I know things like this were used on the IIgs (also on the C64). Both provide scanline synchronous interrupts. So it's just a matter of counting scanline interrupts and then delaying a bit more to wait for the correct position within each line to apply changes to the video registers at the correct time.

The IIe does not have scanline interrupts. Just a register to poll the vertical retrace state. So synchronizing setting changes with individual lines, or even specific pixel areas within a line, is hard (basically requires to lock up the CPU doing nothing else but counting clock cycles, to do the proper pixel timing).

I know there are some modern demos for the IIe using the technique, switching between text and graphics modes, for example, in between pixels of each scan line, to show a little text frame surrounded by graphics.

If Dazzle Draw was indeed switching video modes in between lines/pixels, than that would be the first "real world application" from back in the day I know of.

But I'll need to have a look what it is actually doing. And if my suspicion is even right...

**Comment by misterblack1** [comment]
I was thinking about this too -- but I can't imagine this is what it is doing? It seems to work flawlessly and without any glitching -- and counting cycles on a 1985 program sounds like a bit much? Especially as it would be doing it mid scan line, as when you drop down a menu over the color image, the menu is in monochrome while the stuff to the left and right is perfectly in color.

Do you want me to image this disk of Dazzle Draw I have that is doing this? It seems I have another copy of it that doesn't have this effect. What is funny is the Video 7 enhancer isn't really compatible with the older Video 7 extra modes at all, like the text foreground/background color. The only thing I've seen it do is full screen monochrome like with Apple ][ Desktop, so I was frankly shocked when I saw it doing this selective monochrome mode in Dazzle Draw! 

Perhaps it is using that extra 8th bit in video memory to somehow do this?  The bit normally used for orange/blue in HGR? I'm not a software developer so I don't have a great handle on how DHGR works. Let me test this selective thing on the Apple/Video 7 RGB card (as I was testing at that point on the Enhancer IIe.)

**Comment by misterblack1** [comment]
Ok yes, just tested on the Apple 80col RGB card (Video 7 design) and the selective monochrome works on it as well. So it's not just the enhancer IIe (and the Enhancer IIc) that supports it.  

Now I didn't mention but when looking at the screens in Dazzle Draw via the A2DVI, all just looks normal with extremely fringed text, etc. The only thing I think that makes sense to me is the 8th bit (bit 7) used in HGR to select the shifted colors that is being used here to denote monochrome mode. I think normally otherwise that bit is simply ignored by the video hardware while in DHGR mode? 

I just checked the version of Dazzle Draw that does not do the selective monochrome, and it's dated 1984 in the About Dazzle Draw box. On the screenshots above, it's the 1985 one that does it -- so I guess something that Broderbund fixed in a newer version specifically to better support RGB output devices? My Apple IIe RGB card is dated 1985 and so is the Enhancer IIe RGB board.

**Comment by misterblack1** [comment]
Comparing the two version of Dazzle Draw over RGB (Apple IIe Extended RGB card)
![DD 1984](https://github.com/user-attachments/assets/8a89aaad-e8a7-4aa3-bff1-bbb849a91d20)
![DD 1985](https://github.com/user-attachments/assets/2cf6f6c9-6993-4389-845e-a9d7fe7652e4)

**Comment by ThorstenBr** [comment]
You are probably right - your last pictures gives it away. It has to be something in the data itself. Indeed, bit 7 of each screen data byte is unused in DHGR. That is very likely what they used to switch between color and monochrome - on a per byte (7 monochrome pixels) basis.

That's a feature I wasn't aware of. Neither is is implemented by any of the other analog VGA cards. But if it's just a matter of "checking bit 7", that's probably something that could be added to the rendering code - so A2DVI could also emulate this advanced behavior.

Can you pack and attach the disk which has that feature? Or do you know which of the asimov DazzleDraw versions does this - so I don't start investigating with the wrong disk image:
https://mirrors.apple2.org.za/ftp.apple.asimov.net/images/productivity/graphics/dazzle_draw/

I can verify pretty quickly if they are indeed messing with bit 7.

(That's one of the cool things about these PICO based expansion cards. The PICO sees every bus cycle, every address and data byte that the 6502 handles. It's fairly easy to add logging or other debugging code on the PICO. So monitoring or logging things which would normally be only possible in a software emulator, are suddenly also possible while working with the real hardware...)

**Comment by misterblack1** [comment]
OK I tried a few from Asimov and yeah one of these is the old version that does not do the selective monochrome. I've attached the two relevant versions. 

Dazzle Draw (Brutus Crack).DSK - Doesn't run

dazzle_draw.dsk - Does NOT do selective monochrome (so must be old version aka Control)
Dazzle Draw v1.2 (Broderbund-1988).dsk - This DOES selective monochrome

dazzledraw1.dsk - Also does selective monochrome, same version as the 1.2 above.
dazzledraw2.dsk - Is the slideshow disk

Dazzle Draw 1.2.dsk - Also does the selective monochrome, same version as the one above.
[dazzle_draw.zip](https://github.com/user-attachments/files/17066971/dazzle_draw.zip)

**Comment by misterblack1** [comment]
And yes so cool about being able to debug this quickly and easily!

**Comment by misterblack1** [comment]
More DHGR selective monochrome in use on the Apple Color RGB demo disk even:

![More selective monochrome](https://github.com/user-attachments/assets/d453a9e5-330f-4798-a094-6caf5dfb160e)
[AppleII80columnRGBColorCard-DOS.zip](https://github.com/user-attachments/files/17067103/AppleII80columnRGBColorCard-DOS.zip)

**Comment by ThorstenBr** [comment]
Well, we are getting there...

![image](https://github.com/user-attachments/assets/f0acd7d8-27f9-4e3a-a013-67e455f70d5d)

And I stand corrected concerning "*neither implemented by the analog VGA cards*". Turns out, the "Double-HIRES with Monochrome pixels" video mode is one of the "Video 7" video modes, which had already been implemented by David Kuder for his "analog VGA" card. Props to him. My A2DVI firmware inherits its basic video rendering logic from David's project. I have now also ported the missing Video 7 video modes for A2DVI. Indeed, Dazzle Draw does look better with this.

Looks promising, but might still have rendering issues. It's getting late over here. I'll have some more time this weekend to look at these modes in more details.

If you want to have a go with testing the current build - I have attached the latest firmware build:
[A2DVI_v1.3A1.zip](https://github.com/user-attachments/files/17067393/A2DVI_v1.3A1.zip)

**Comment by misterblack1** [comment]
Awesome, I'm literally in the middle of making a video about the A2DVI card, so I'll be leading this test firmware on specifically for the video. And I'm not surprised David Kuder implemented it on the VGA card! Side note, I connected up my VGA only LCD via a $3 HDMI-VGA adapter and that worked flawlessly. Now if only I could find David's card -- I think I left it in one of my Apple II machines I'm not sure which.

**Comment by misterblack1** [comment]
NICE! Ok I gave it some tests it's like 90% there. The HGR 16 color mode seems to work perfectly, and then the selective monochrome seems to work for the most part. The bar graph display from the Apple RGB demo disk has some color fringing here and there but it's nearly there. I assume David Kuder's code is probably just like that too -- so maybe some tweaks are needed to both?

**Comment by misterblack1** [comment]
Ok example of how it looks on the 1.3A1 firmware:
![Selective Monochrome FW1 3A1](https://github.com/user-attachments/assets/a3d671f1-6199-4bb3-9fba-d2748aeab97e)

Noticed the fringed text which isn't seen on the RGB card.

**Comment by misterblack1** [comment]
OK ran into another issue, if you boot the Apple II RGB card demo, and pick slide show. This HGR 16 color image will be displayed, which is somehow stretched and messed up via the A2DVI but works fine on the real RGB card. The other 16 color HGR images work fine though.
Video 7 RGB Card:
![16 color HGR Video 7 RGB Card](https://github.com/user-attachments/assets/5c38a024-dbb2-4816-adc3-c9e31592c8fe)
FW1.3A1:
![16 color HGR FW 1 3A1](https://github.com/user-attachments/assets/ee5d53ae-4d50-451b-960e-b5fc6804709e)

**Comment by ThorstenBr** [comment]
Three quick fixes: firmware 1.3A2:
[A2DVI_v1.3A2.zip](https://github.com/user-attachments/files/17070463/A2DVI_v1.3A2.zip)

The color fringes of monochrome pixels in the advanced V7 mode are gone:
![image](https://github.com/user-attachments/assets/8a0aa8f7-0f0f-4897-82b8-ecf08763093f)

Also the "strech" issue with the 160x192 Video-7 mode is fixed:
![image](https://github.com/user-attachments/assets/95ea1cbe-58e0-4e49-a99f-908218209380)

**Comment by misterblack1** [comment]
Simply amazing!! Software defined hardware FOR THE WIN!!!

**Comment by ThorstenBr** [comment]
Indeed. And until not too long ago, HDMI signal generation would have been an application very clearly only possible with FPGAs (or ASICs). That this can now be easily "bit banged" in software, using a tiny, super cheap microcontroller (worth just a few cents on digikey), is simply mind boggling. And the controller isn't even running at its limit yet...

**Comment by misterblack1** [comment]
Yes! This is what I am marvelling at in the video! How on earth are we doing this with something so cheap!?! Next up really is a version of the card design with the RP2040 right on the PCB so nor more Pi Pico carrier required, bringing the cost down even further. Anyway, I'll close this issue since you totally fixed everything!
