### ISSUE TITLE
Unimplemented Video 7 mode

### ISSUE THREAD

**Issue by misterblack1** [ThorstenBr/A2DVI-Firmware#9]
I was testing the Video 7 mode against a real Video 7 card and there is one unimplemented mode:

![Video 7 16 color HGR mode](https://github.com/user-attachments/assets/d4c9b0b4-f6a6-4e1c-b9d1-b1a72eb23976)
![Video 7 16 color HGR mode via A2DVI](https://github.com/user-attachments/assets/57e828e0-8981-4e15-8d90-30c81fb26132)
![Video 7 16 color HGR mode menu item 10](https://github.com/user-attachments/assets/26260e4b-c2f8-4b56-800f-2daa4763e7b0)

The text color modes all seem to work, but this 16 color graphics mode doesn't work. Some of the other modes on this demo disk don't work either (on the real card as well) as the card this disk came from did not have 64k of RAM on it, so it only supported 80 col text but not DHGR. Because of that, there are some modes that no longer work on the later Video 7 RGB card that has a full 64k of RAM on it. (This is what I am testing with right now, the Apple RGB Card)

On the attached demo disk, go into option 2 from the main menu, then pick option 10 to see the unimplemented mode in operation.

[Taxan-RGB-Demo.zip](https://github.com/user-attachments/files/17053565/Taxan-RGB-Demo.zip)

**Comment by ThorstenBr** [comment]
Yes, I just ported the 40 column color text mode a short while ago. The V7 graphics mode are not ported yet. Takes a bit of effort to port and optimize the modes to generate valid DVI protocol data. I can have a look at the graphics modes in the next few days, and maybe already provide a firmware for testing. I don't even have a Video7 card myself. So it'd be good if there was someone who could test/verify. And you're the first one to even ask about V7... :-)

**Comment by misterblack1** [comment]
Heh awesome! They are somewhat rare things so it would be awesome to have it fully implemented, not that anything really uses any of it. It's kind of hilarious Apple didn't even port these modes that their own branded Video 7 card supported to the IIgs.

**Comment by misterblack1** [comment]
Seems the HGR 16 color mode uses the exrta ram in the AUX bank to store color (foreground/background) information for cells on the HGR screen that are the same size as a text character. Each 8 bit value in aux RAM is 4 bits bg, 4 bits fg and which means the graphics color is just like how it works on the ZX Spectrum (Hello color clash!) It means if this is implemented some ZX spectrum ports of games would be possible that would essentially give identical color fidelity, other than the palette being a bit different on the Apple II.

The Apple Demo disk shows this off with the splash screen with the Apple Logo but then later under Business Demonstration from the menu, you can see the same graph I screenshotted up above from the Taxan disk. 

They implemented it this was as the first Video 7 RGB card did not have the whole 64k of AUX ram, but instead had 4K, enough to display 80 column text. So they took advantage of that extra AUX RAM to give those cells of color on HGR mode... working within the limitations of the original card... 

[AppleII80columnRGBColorCard-DOS.zip](https://github.com/user-attachments/files/17067192/AppleII80columnRGBColorCard-DOS.zip)

**Comment by ThorstenBr** [comment]
Thanks, that is a very good disk for testing!

Some modes are already working well now (with new firmware in other issue):
![image](https://github.com/user-attachments/assets/7eb1bf80-caff-4918-bab4-e25c7d4f2ebe)

But there are some obvious issues. This happens with both my latest A2DVI firmware and with David's VGA firmware: 
![image](https://github.com/user-attachments/assets/14be2bed-48e9-4141-afca-b87e7c75baba)
So some of the basic rendering logic isn't quite right yet.

Unfortunately I don't have a V7 card to compare. If you end up with any raw video footage showing how the video nodes look on real hardware, that would be really helpful in quickly spotting what is already right and what isn't.

Otherwise, already looking forward to your video on the subject... (*8bit dance party!* 🕺 🕺 🕺 ;-) )

*Thorsten*

**Comment by misterblack1** [comment]
I posted some pics in the selective monochrome issue  -- but I would say the HGR-16 color mode is now nearly fully implemented and appears to work perfectly, other than the one picture which is rendering incorrectly. (Sorry it's on the selective monochrome issue.) 

The selective monochrome definitely has some small issues like you were seeing which are not present on the real cards.

**Comment by misterblack1** [comment]
This issue has been fully resolved with Firmware 1.3A2 as seen here:
https://github.com/ThorstenBr/A2DVI-Firmware/issues/8#issuecomment-2362883144
